### ISSUE TITLE
Settings Sync

### ISSUE THREAD

**Issue by deadcoder0904** [burkeholland/react-food-truck#1]
It ain't React specific but more like VSCode specific. It syncs all your current extensions to a github gist so that if you change your computer or reinstall VSCode you don't have to manually install anything.

For more info, checkout [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) 😄

**Comment by mehrdad-shokri** [comment]
I don't think it's food truck related. ;)

**Comment by deadcoder0904** [comment]
Cool
