### ISSUE TITLE
Import Cost

### ISSUE THREAD

**Issue by aharl** [burkeholland/react-food-truck#4]
I really love the import cost plugin, and was using it before installing react food truck, but it is really a hog on cpu and memory. You can peruse the issue queue for it to see numerous reports of memory leaks or long startup times. [https://github.com/wix/import-cost/issues](https://github.com/wix/import-cost/issues) It would be nice to not have it as a dependency for react-food-truck so that it can be disabled or enabled as needed.

**Comment by burkeholland** [comment]
Oooooh - did not know about this. I was actually on the fence about including it at all since it's not really anything to do with React. I may pull it out altogether.
